# Generated by Django 3.2.7 on 2022-03-05 14:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20220301_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='convert',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
