# Generated by Django 3.2.7 on 2022-03-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_alter_page_convert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='convert',
            field=models.TextField(),
        ),
    ]
